from tkinter import messagebox


def pattern_count(text, pattern):
    count = 0
    for i in range(len(text) - len(pattern) + 1):
        if text[i:i + len(pattern)] == pattern:
            count = count + 1
    return count


Test = "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGT" \
       "TTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCAT" \
       "GACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCT" \
       "TCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGACGGAGCGGGATTACGAAAGCATGATCATGGC" \
       "TGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTA" \
       "CTCTGCCTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATT" \
       "GAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAGCCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTT" \
       "TACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC"

pattern1 = "TGATCA"
t = "ACTGTACGATGATGTGTGTCAAAG"

length = len("ACTGTACGATGATGTGTGTCAAAG")
counting = pattern_count("ACTGTACGATGATGTGTGTCAAAG", "TGT")

title = "Pattern Count"
messagebox.showinfo(title, f"The pattern count is {counting}")

for x in range(len(t) - len("TGT") + 1):
    print(x)
    myTest = t[x:x + len("TGT")]
    print(myTest)
